package ca.bc.gov.nrs.fta.tenure.tab.details;

/**
 * Which sections and fields FTA100 shows for this file (the package's {@code p_show_*}
 * indicators and the action's hide flags), and its file-type-dependent labels.
 */
public record TenureDetailsLayout(
    String licenseeLabel,
    boolean recreation,
    boolean oldRecreation,
    boolean privateMark,
    boolean showDistrict,
    boolean showFnAgreement,
    boolean showMapNotation,
    boolean showZone,
    boolean showSalvage,
    boolean showSfl,
    boolean showFup,
    boolean showTerm,
    boolean showTenureTerm,
    boolean showExtension,
    boolean showReplaceable,
    boolean showDesignate,
    String extensionCountLabel,
    boolean showEstTotalVol,
    boolean showPulpwoodAac,
    boolean showLocationArea,
    boolean showDepositPurpose,
    boolean showMarkPurpose,
    String purposeField,
    String annualRentLabel,
    boolean showDeposits,
    boolean showTimberLicenceAreas,
    boolean grossArea,
    boolean showMinor,
    boolean showBcts,
    boolean showBctsFund,
    boolean showPaymentMethod,
    boolean showSpatialLater,
    boolean showAac,
    boolean showMark,
    String markDisplay,
    boolean showWasteAssess,
    boolean showFrz,
    boolean showMarkAdditional,
    boolean showQuotaType,
    String cruiseBasedLabel,
    boolean showOccupancy,
    boolean showPulpwoodAgreement) {}
